CREATE TABLE "usuario" (
	"id_usuario" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nombre" VARCHAR(30),
	"email" VARCHAR(30),
	"fecha_registro" DATE,
	PRIMARY KEY("id_usuario")
);




CREATE TABLE "publicacion" (
	"id_publicacion" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"titulo" VARCHAR(30),
	"contenido" TEXT,
	"fecha_creacion" DATE,
	"id_usuario" INTEGER,
	"id_blog" INTEGER,
	PRIMARY KEY("id_publicacion")
);




CREATE TABLE "blog" (
	"id_blog" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"titulo" VARCHAR(100),
	"descripcion" TEXT,
	"fecha_creacion" DATE,
	"id_usuario" INTEGER,
	PRIMARY KEY("id_blog")
);



ALTER TABLE "publicacion"
ADD FOREIGN KEY("id_usuario") REFERENCES "usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "blog"
ADD FOREIGN KEY("id_usuario") REFERENCES "usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "publicacion"
ADD FOREIGN KEY("id_blog") REFERENCES "blog"("id_blog")
ON UPDATE NO ACTION ON DELETE NO ACTION;