--
-- PostgreSQL database dump
--

\restrict lxtXUNLJeqdK6IRBEiET8ZXgyCetiZwEkJxxV9EeWgLB0j5was0jC6eUjz9IHhc

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actor (
    id_actor integer NOT NULL,
    nombre character varying(50),
    fecha_nacimiento date
);


ALTER TABLE public.actor OWNER TO postgres;

--
-- Name: actor_id_actor_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.actor ALTER COLUMN id_actor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actor_id_actor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: elenco; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elenco (
    id_elenco integer NOT NULL,
    id_actor integer,
    id_pelicula integer
);


ALTER TABLE public.elenco OWNER TO postgres;

--
-- Name: elenco_id_elenco_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.elenco ALTER COLUMN id_elenco ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.elenco_id_elenco_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pelicula; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pelicula (
    id_pelicula integer NOT NULL,
    titulo character varying(50),
    "año_lanzamiento" integer
);


ALTER TABLE public.pelicula OWNER TO postgres;

--
-- Name: pelicula_id_pelicula_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pelicula ALTER COLUMN id_pelicula ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pelicula_id_pelicula_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: actor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.actor (id_actor, nombre, fecha_nacimiento) FROM stdin;
\.


--
-- Data for Name: elenco; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.elenco (id_elenco, id_actor, id_pelicula) FROM stdin;
\.


--
-- Data for Name: pelicula; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pelicula (id_pelicula, titulo, "año_lanzamiento") FROM stdin;
\.


--
-- Name: actor_id_actor_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.actor_id_actor_seq', 1, false);


--
-- Name: elenco_id_elenco_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.elenco_id_elenco_seq', 1, false);


--
-- Name: pelicula_id_pelicula_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pelicula_id_pelicula_seq', 1, false);


--
-- Name: actor actor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actor
    ADD CONSTRAINT actor_pkey PRIMARY KEY (id_actor);


--
-- Name: elenco elenco_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elenco
    ADD CONSTRAINT elenco_pkey PRIMARY KEY (id_elenco);


--
-- Name: pelicula pelicula_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pelicula
    ADD CONSTRAINT pelicula_pkey PRIMARY KEY (id_pelicula);


--
-- Name: elenco elenco_id_actor_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elenco
    ADD CONSTRAINT elenco_id_actor_fkey FOREIGN KEY (id_actor) REFERENCES public.actor(id_actor);


--
-- Name: elenco elenco_id_pelicula_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elenco
    ADD CONSTRAINT elenco_id_pelicula_fkey FOREIGN KEY (id_pelicula) REFERENCES public.pelicula(id_pelicula);


--
-- PostgreSQL database dump complete
--

\unrestrict lxtXUNLJeqdK6IRBEiET8ZXgyCetiZwEkJxxV9EeWgLB0j5was0jC6eUjz9IHhc

