--
-- PostgreSQL database dump
--

\restrict glk9h5tU4NmzbC7J3rRDuT9wexsSbJHEZlaYzbfhR16Daz4OcVIku3YvA3n5X0k

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id_cliente integer NOT NULL,
    nombre character varying(30),
    telefono integer
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- Name: cliente/pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."cliente/pedido" (
    id integer NOT NULL,
    id_cliente integer,
    id_pedido integer
);


ALTER TABLE public."cliente/pedido" OWNER TO postgres;

--
-- Name: cliente/pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."cliente/pedido" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."cliente/pedido_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente_id_cliente_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cliente ALTER COLUMN id_cliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_cliente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu (
    id_menu integer NOT NULL,
    nombre character varying(50),
    precio numeric,
    descripcion character varying(255)
);


ALTER TABLE public.menu OWNER TO postgres;

--
-- Name: menu/pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."menu/pedido" (
    id integer NOT NULL,
    id_menu integer,
    id_pedido integer
);


ALTER TABLE public."menu/pedido" OWNER TO postgres;

--
-- Name: menu/pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."menu/pedido" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."menu/pedido_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_id_menu_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu ALTER COLUMN id_menu ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_id_menu_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido (
    id_pedido integer NOT NULL,
    fecha date,
    estado boolean,
    detalle_pedido character varying(255)
);


ALTER TABLE public.pedido OWNER TO postgres;

--
-- Name: pedido_id_pedido_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedido ALTER COLUMN id_pedido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_id_pedido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id_cliente, nombre, telefono) FROM stdin;
\.


--
-- Data for Name: cliente/pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."cliente/pedido" (id, id_cliente, id_pedido) FROM stdin;
\.


--
-- Data for Name: menu; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.menu (id_menu, nombre, precio, descripcion) FROM stdin;
\.


--
-- Data for Name: menu/pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."menu/pedido" (id, id_menu, id_pedido) FROM stdin;
\.


--
-- Data for Name: pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedido (id_pedido, fecha, estado, detalle_pedido) FROM stdin;
\.


--
-- Name: cliente/pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."cliente/pedido_id_seq"', 1, false);


--
-- Name: cliente_id_cliente_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_cliente_seq', 1, false);


--
-- Name: menu/pedido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."menu/pedido_id_seq"', 1, false);


--
-- Name: menu_id_menu_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_id_menu_seq', 1, false);


--
-- Name: pedido_id_pedido_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedido_id_pedido_seq', 1, false);


--
-- Name: cliente/pedido cliente/pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."cliente/pedido"
    ADD CONSTRAINT "cliente/pedido_pkey" PRIMARY KEY (id);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente);


--
-- Name: menu/pedido menu/pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."menu/pedido"
    ADD CONSTRAINT "menu/pedido_pkey" PRIMARY KEY (id);


--
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (id_menu);


--
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (id_pedido);


--
-- Name: cliente/pedido cliente/pedido_id_cliente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."cliente/pedido"
    ADD CONSTRAINT "cliente/pedido_id_cliente_fkey" FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente);


--
-- Name: cliente/pedido cliente/pedido_id_pedido_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."cliente/pedido"
    ADD CONSTRAINT "cliente/pedido_id_pedido_fkey" FOREIGN KEY (id_pedido) REFERENCES public.pedido(id_pedido);


--
-- Name: menu/pedido menu/pedido_id_menu_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."menu/pedido"
    ADD CONSTRAINT "menu/pedido_id_menu_fkey" FOREIGN KEY (id_menu) REFERENCES public.menu(id_menu);


--
-- Name: menu/pedido menu/pedido_id_pedido_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."menu/pedido"
    ADD CONSTRAINT "menu/pedido_id_pedido_fkey" FOREIGN KEY (id_pedido) REFERENCES public.pedido(id_pedido);


--
-- PostgreSQL database dump complete
--

\unrestrict glk9h5tU4NmzbC7J3rRDuT9wexsSbJHEZlaYzbfhR16Daz4OcVIku3YvA3n5X0k

